#' Compute Cohen's f-squared for One or Two Linear Models
#'
#' @description
#' This takes one or two linear models and returns the value of f^2 as outlined in Cohen (1988).
#'
#' @details
#' #' f² is a measure of the *local* effect size of a model. When using one model with the function e.g., `cohen_f2(model0)`, the researcher is testing to see if the difference between the values predicted by using the model are different that the actual values.
#'
#' With 1 model, the aim is to reduce f^2 as close to zero as possible or to at least below the moderate threshold. That is the effect size of using the model rather than the actual data is minimal.
#'
#' When comparing two models using `cohen_f2(model0,model1)` the researcher can determine if the *effect* of including the additional predictor variables in model1 is significant enough to justify the increased complexity of the model compared to model0. In this case, the hope is to maximise the value of f² and usually if f² is less than an acceptable threshold chosen by the researcher then it is wise **not** to accept the more complex model. If `model0` and `model1` have different numbers of parameters, then it is recommended to use the adjusted r-squared values in this test.
#'
#' Cohen suggested the following cut off values for f^2
#'
#' f^2 >= 0.02 : Small
#' f^2 >= 0.15 : Moderate
#' f^2 >= 0.35 : Large
#'
#' A reasonable acceptance threshold might be thought of as 0.04, i.e. double the Small effect size value. However, this recommendation is arbitrary
#'
#' @param baseModel Either:
#'   * a model generated by a call to lm(), or
#'   * a single numeric value in [0,1) representing R-squared.
#'
#' @param comparisonModel Optional. Either:
#'   * a model generated by a call to lm(), or
#'   * a single numeric value in [0,1) representing R-squared.
#'   If omitted, f² is computed for `baseModel` alone.
#'
#' @param use_adjusted Logical, default `FALSE`. If `TRUE` and either
#'   `baseModel` or `comparisonModel` is an `lm` object, adjusted R²
#'   (`$adj.r.squared`) is used instead of R² (`$r.squared`) for that
#'   argument. If the argument is numeric, `use_adjusted` has no effect.
#'
#' @return A single numeric value: Cohen's f².
#' @export
#'
#' @importFrom tibble tibble
#'
#' @examples
#'
#' library(tibble)
#'
#' ## Generate some test data where y = x^2 + noise
#' df <- tibble::tibble(x = seq(1, 10, length.out = 100), y = x^2 + rnorm(length(x)))
#'
#' ## Create two simple linear models
#' model0 <- lm(y ~ x, data = df)
#' model1 <- lm(y ~ x + I(x^2), data = df)
#'
#' ## Check the fit of each model to the data
#' cohen_f2(model0)
#' cohen_f2(model1)
#'
#' ## Check if model1 is a better fit for the data than model0
#' cohen_f2(model0, model1)
#'
cohen_f2 <- function(baseModel,
                     comparisonModel,
                     use_adjusted = FALSE) {

  R2_base <- .timefitteR_get_r2(
    obj = baseModel,
    use_adjusted = use_adjusted
  )

  if (missing(comparisonModel)) {
    # single model f²

    f_2 <- R2_base / (1 - R2_base)

  } else {
    # comparison of models f²

    R2_comp <- .timefitteR_get_r2(
      obj = comparisonModel,
      use_adjusted = use_adjusted
    )

    f_2 <- (R2_comp - R2_base) / (1 - R2_comp)
  }

  return(f_2)
}

#' extract R² from lm or numeric
.timefitteR_get_r2 <- function(obj,
                               arg_name = NULL,
                               use_adjusted = FALSE) {

  if (is.null(arg_name)) {
    arg_name <- rlang::caller_arg(obj)
  }

  if (inherits(obj, "lm")) {
    sm <- summary(obj)
    r2 <- if(isTRUE(use_adjusted)) sm$adj.r.squared else sm$r.squared
  } else if (is.numeric(obj) && length(obj) == 1L) {
    r2 <- obj
  } else {
    rlang::abort(
      message = glue::glue("`{arg_name}` must be either an object of class 'lm' or a single numeric R-squared value."),
      class   = "timefitteR_cohen_bad_arg",
      call    = NULL
    )
  }

  if (!is.finite(r2) || r2 < 0 || r2 >= 1) {
    rlang::abort(
      message = glue::glue("R-squared value derived from `{arg_name}` must be finite and in [0, 1); got {format(r2)}."),
      class   = "timefitteR_cohen_bad_r2",
      call    = NULL
    )
  }

  r2
}
